
postgres: &postgres
  adapter: postgresql
  min_messages: WARNING

development:
  <<: *postgres
  database: tithe_db

test:
  <<: *postgres
  database: tithe_db_test

production:
  <<: *postgres
  database: tithe_db